FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y libmagic1

COPY pyproject.toml ./
COPY src/config.py ./src/
COPY src/db ./src/db
COPY src/api ./src/api
COPY src/api/requirements.txt ./

RUN pip install . && pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app/src

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
